/**
 * Convex Service
 * 
 * Service wrapper for interacting with Convex from Express backend.
 * This allows the Express backend to use Convex as its database layer.
 * 
 * Uses ConvexHttpClient for Node.js backends.
 */

const { ConvexHttpClient } = require("convex/browser");

class ConvexService {
  constructor() {
    // Initialize Convex URL
    // CONVEX_URL is set by Convex CLI or can be provided via environment variable
    // Format: https://your-deployment.convex.cloud
    this.convexUrl = process.env.CONVEX_URL || process.env.VITE_CONVEX_URL;
    
    if (!this.convexUrl) {
      console.warn('⚠️  CONVEX_URL not set. Convex service will not be available.');
      this.client = null;
      return;
    }

    // Remove trailing slash if present
    this.convexUrl = this.convexUrl.replace(/\/$/, '');
    
    // Initialize Convex HTTP client
    this.client = new ConvexHttpClient(this.convexUrl);
    
    // Import API routes dynamically (will be generated by Convex)
    // For now, we'll use string paths - these will match the function exports
    this.api = null;
    
    try {
      // Try to import generated API (may not exist until Convex generates it)
      this.api = require('../convex/_generated/api');
    } catch (e) {
      console.warn('⚠️  Convex generated API not found. Using string paths.');
      console.warn('   Run "npx convex dev" to generate API definitions.');
    }
    
    console.log('✅ Convex service initialized:', this.convexUrl);
  }

  /**
   * Execute a Convex query
   * @param {string} path - Query path (e.g., "queries/users:getByEmail")
   * @param {object} args - Query arguments
   * @returns {Promise<any>} Query result
   */
  async query(path, args = {}) {
    if (!this.client) {
      throw new Error('Convex client not initialized. Set CONVEX_URL environment variable.');
    }

    // Convex expects paths like "queries/users:getByEmail" (file path without extension, colon, function name)
    let fullPath = path;
    if (path.includes(':')) {
      // Path like "users:getByEmail" -> convert to "queries/users:getByEmail"
      if (!path.startsWith('queries/') && !path.startsWith('mutations/')) {
        const [module, func] = path.split(':');
        fullPath = `queries/${module}:${func}`;
      }
    } else {
      // Just function name, assume queries directory
      fullPath = `queries/${path}`;
    }

    try {
      return await this.client.query(fullPath, args);
    } catch (error) {
      console.error('Convex query error:', error);
      console.error('  - Path:', fullPath);
      console.error('  - Args:', args);
      console.error('  - Error name:', error.name);
      console.error('  - Error message:', error.message);
      console.error('  - Error stack:', error.stack);
      // Preserve more error details
      const errorMessage = error.message || error.toString();
      throw new Error(`Convex query failed: ${errorMessage}`);
    }
  }

  /**
   * Execute a Convex mutation
   * @param {string} path - Mutation path (e.g., "mutations/users:create")
   * @param {object} args - Mutation arguments
   * @returns {Promise<any>} Mutation result
   */
  async mutation(path, args = {}) {
    if (!this.client) {
      throw new Error('Convex client not initialized. Set CONVEX_URL environment variable.');
    }

    // Convex expects paths like "mutations/users:create" (file path without extension, colon, function name)
    let fullPath = path;
    if (path.includes(':')) {
      // Path like "users:create" -> convert to "mutations/users:create"
      if (!path.startsWith('queries/') && !path.startsWith('mutations/')) {
        const [module, func] = path.split(':');
        fullPath = `mutations/${module}:${func}`;
      }
    } else {
      // Just function name, assume mutations directory
      fullPath = `mutations/${path}`;
    }

    try {
      return await this.client.mutation(fullPath, args);
    } catch (error) {
      console.error('Convex mutation error:', error);
      console.error('  - Path:', fullPath);
      console.error('  - Args:', args);
      console.error('  - Error name:', error.name);
      console.error('  - Error message:', error.message);
      console.error('  - Error stack:', error.stack);
      // Preserve more error details
      const errorMessage = error.message || error.toString();
      throw new Error(`Convex mutation failed: ${errorMessage}`);
    }
  }

  /**
   * Execute a Convex action
   * @param {string} path - Action path (e.g., "actions/users:sendEmail")
   * @param {object} args - Action arguments
   * @returns {Promise<any>} Action result
   */
  async action(path, args = {}) {
    if (!this.client) {
      throw new Error('Convex client not initialized. Set CONVEX_URL environment variable.');
    }

    // Convex expects paths like "actions/users:sendEmail" (file path without extension, colon, function name)
    let fullPath = path;
    if (path.includes(':')) {
      if (!path.startsWith('actions/')) {
        const [module, func] = path.split(':');
        fullPath = `actions/${module}:${func}`;
      }
    } else {
      fullPath = `actions/${path}`;
    }

    try {
      return await this.client.action(fullPath, args);
    } catch (error) {
      console.error('Convex action error:', error);
      throw new Error(`Convex action failed: ${error.message}`);
    }
  }

  /**
   * Check if Convex service is available
   */
  isAvailable() {
    return this.client !== null;
  }
}

// Export singleton instance
module.exports = new ConvexService();

